version: '3.5'

services:
    grafana:
        image: grafana/grafana
        volumes:
            - ./grafana_data:/var/lib/grafana
            - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
            - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
            - ./grafana/dashboards/:/etc/grafana/provisioning/dashboards/
        environment: 
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            GF_SERVER_DOMAIN: ${GF_SERVER_DOMAIN}
            GF_SERVER_ROOT_URL: ${GF_SERVER_ROOT_URL}
        ports:
            - "${GRAFANA_PORT}:3000"

    database:
        image: mariadb:10.4
        volumes:
            - ./db:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--innodb-flush-method=littlesync', '--innodb-use-native-aio=OFF']
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 1
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    app:
        build: app
        volumes:
            - ${MYSQL_SOCK}:/run/mysqld/mysqld.sock
        environment: 
            GRAFANA_DATABASE: ${MYSQL_DATABASE}
            GRAFANA_USER: ${MYSQL_USER}
            MYSQL_PWD: ${MYSQL_PASSWORD}
            SCANNER_HOST: ${SCANNER_HOST}
            SCANNER_PORT: ${SCANNER_PORT}
            SCANNER_USER: ${SCANNER_USER}
            SCANNER_PASSWORD: ${SCANNER_PASSWORD}
            SCANNER_DATABASE: ${SCANNER_DATABASE}
            STATUS_DOWN: ${STATUS_DOWN}
            CLEANUP_DAYS: ${CLEANUP_DAYS}
        depends_on:
            - database
            - grafana

